server:
  port: 8030

spring:
  application:
    name: ms-authorization-server
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seguranca
    username: root
    password: root